### ISSUE TITLE
The problem depending on xterm in melodic 

### ISSUE THREAD

**Issue by hi-kondo** [seed-solutions/seed_r7_ros_pkg#70]
In case of Ubuntu18.04 (melodic), xterm may not be installed at default.
If it is not installed, seed_r7_samples/demo.launch will be crushed.

#69

**Comment by y-shiigi** [comment]
please run ``sudo apt install xterm``

or 

change the launch-prefix from ``xterm -e``  to ``gnome-terminal --`` at [demo.launch](https://github.com/seed-solutions/seed_r7_ros_pkg/blob/43d71440ca5256fa9f7b350e9186ad920936ee89/seed_r7_samples/launch/demo.launch#L19-L28)
