### ISSUE TITLE
What is the differences between TypeF and TypeG

### ISSUE THREAD

**Issue by kenichi-ohara** [seed-solutions/seed_r7_ros_pkg#76]
Recently, the Model of typeG has beed added as the robot model to the repository.
Could you please show what are the differences between typeF and typeG.
(It is really useful information for the SEED-Noid developer.)

**Comment by y-shiigi** [comment]
@kenichi-ohara 
These basic axis-configurations are almost same. The main differences are below:
* size
<img src="https://user-images.githubusercontent.com/12426780/80568071-442c3580-8a31-11ea-9ab6-e6ce07527a66.png" width=50%>

* battery
<img src="https://user-images.githubusercontent.com/12426780/80568164-7473d400-8a31-11ea-9177-e8b992398a87.png" width=70%>

* sensor
<img src="https://user-images.githubusercontent.com/12426780/80568204-8a819480-8a31-11ea-81ce-1e55fc4d3988.png" width=70%>

The joint limits and the maximum velocites are being experimented now, but I think that they will not be deviated significantly from [the current settings](https://github.com/seed-solutions/seed_r7_ros_pkg/blob/43d71440ca5256fa9f7b350e9186ad920936ee89/seed_r7_description/urdf/typeG_upperbody/noid_upper_typeg.urdf.xacro). (i found typo typef.. it's typeg)

Also, though not directly related to ROS, the performance of motor driver (SEED Driver) has been improved.

**Comment by kenichi-ohara** [comment]
Thank you very much!
I can understand the differences!
